"""Interactive Streamlit dashboard for the PJM energy forecasting project."""
from __future__ import annotations

from pathlib import Path

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

ROOT = Path(__file__).resolve().parent
DATA_FILE = ROOT / "PJME_hourly.csv"
WEATHER_FILE = ROOT / "data" / "weather_data.csv"
OUTPUT_DIR = ROOT / "outputs"
PROCESSED_FILE = ROOT / "data" / "processed" / "processed_data.csv"

st.set_page_config(page_title="PJM Energy Forecasting", page_icon="⚡", layout="wide")


@st.cache_data(show_spinner=False)
def load_csv(path: str, dates: bool = True) -> pd.DataFrame:
    return pd.read_csv(path, parse_dates=["Datetime"] if dates else None)


def artifact(path: Path, message: str) -> bool:
    if not path.exists():
        st.info(message)
        return False
    return True


def metric_card(label: str, value: float, suffix: str = "") -> None:
    st.metric(label, f"{value:,.2f}{suffix}")


def overview() -> None:
    st.title("⚡ PJM East Energy Consumption Forecasting")
    st.subheader("24-hour electricity-demand forecasting with XGBoost and weather features")
    st.write(
        "This project estimates PJM East electricity demand one day ahead to support "
        "grid balancing, operational planning, and cost control. It combines historical "
        "load with calendar, lag, rolling-statistic, and weather variables."
    )
    if artifact(OUTPUT_DIR / "model_metrics.csv", "Run `python -m src.model_xgboost` to generate model artifacts."):
        metrics = pd.read_csv(OUTPUT_DIR / "model_metrics.csv").iloc[0]
        cards = st.columns(4)
        with cards[0]: metric_card("MAPE", metrics["MAPE_pct"], "%")
        with cards[1]: metric_card("RMSE", metrics["RMSE_MW"], " MW")
        with cards[2]: metric_card("MAE", metrics["MAE_MW"], " MW")
        with cards[3]: metric_card("R²", metrics["R2"])
    st.markdown("### Forecast contract")
    st.info(
        "At forecast origin **t**, the model predicts demand at **t + 24 hours**. "
        "Training/test records are split by that target timestamp, so the evaluation "
        "does not use future observed load as an input."
    )
    st.markdown("### Success targets from the PRD")
    st.dataframe(pd.DataFrame({"Metric": ["MAPE", "RMSE", "MAE", "R²", "Forecast horizon"], "Target": ["< 5%", "< 500 MW", "< 350 MW", "> 0.90", "24 hours"]}), hide_index=True, use_container_width=True)


def data_and_eda() -> None:
    st.title("Data loading & exploratory analysis")
    if not artifact(DATA_FILE, "PJME_hourly.csv was not found in the project root."):
        return
    data = load_csv(str(DATA_FILE))
    data["Datetime"] = pd.to_datetime(data["Datetime"])
    st.caption(f"Source: PJM East hourly consumption | {len(data):,} raw observations | {data.Datetime.min():%Y-%m-%d} to {data.Datetime.max():%Y-%m-%d}")
    left, right = st.columns([2, 1])
    with left:
        start, end = st.date_input("Date range", value=(data.Datetime.min().date(), data.Datetime.max().date()), min_value=data.Datetime.min().date(), max_value=data.Datetime.max().date())
        selected = data[data.Datetime.between(pd.Timestamp(start), pd.Timestamp(end) + pd.Timedelta(days=1))]
        st.plotly_chart(px.line(selected, x="Datetime", y="PJME_MW", title="Hourly PJM East demand"), use_container_width=True)
    with right:
        st.dataframe(data.PJME_MW.describe().rename("MW").round(2), use_container_width=True)
        st.metric("Raw missing values", int(data.isna().sum().sum()))
    profile = data.assign(hour=data.Datetime.dt.hour, weekday=data.Datetime.dt.day_name()).groupby("hour", as_index=False).PJME_MW.mean()
    st.plotly_chart(px.bar(profile, x="hour", y="PJME_MW", title="Average load by hour of day", labels={"PJME_MW": "Average MW"}), use_container_width=True)
    with st.expander("Raw data preview"):
        st.dataframe(data.head(200), use_container_width=True)
    if (OUTPUT_DIR / "eda_overview.png").exists():
        st.image(str(OUTPUT_DIR / "eda_overview.png"), caption="Saved EDA overview generated by src/eda.py")


def weather() -> None:
    st.title("Weather data integration")
    st.write("Weather acts as an exogenous driver of demand: temperature, humidity, wind speed, pressure, and cloud cover.")
    if not artifact(WEATHER_FILE, "No weather file exists. Run the model pipeline to create one."):
        return
    data = load_csv(str(WEATHER_FILE))
    source = data.get("weather_source", pd.Series(["observed historical weather"])).iloc[0]
    if source == "deterministic_climatology_proxy":
        st.warning("This run uses a deterministic seasonal climatology proxy, not observed weather. Replace `data/weather_data.csv` with historical observed data before interpreting weather importance as production evidence.")
    else:
        st.success("A weather dataset is present. Verify its provenance and timestamp alignment before production use.")
    st.caption(f"Weather source label: `{source}`")
    cols = [c for c in ["Temperature", "Humidity", "WindSpeed", "Pressure", "CloudCover"] if c in data.columns]
    choice = st.multiselect("Weather variables", cols, default=cols[:2])
    if choice:
        subset = data.set_index("Datetime")[choice].resample("7D").mean().reset_index()
        st.plotly_chart(px.line(subset, x="Datetime", y=choice, title="Weekly average weather variables"), use_container_width=True)
    st.dataframe(data.head(100), use_container_width=True)
    st.markdown("**API design:** current conditions use OpenWeather's `/data/2.5/weather`; historical loading is implemented through the Time Machine endpoint, which requires suitable OpenWeather access. API keys are loaded from `OPENWEATHER_API_KEY`, never hard-coded.")


def features() -> None:
    st.title("Feature engineering")
    groups = pd.DataFrame([
        ["Calendar", "hour, day of week, month, quarter, year", "Captures regular demand patterns"],
        ["Cyclical", "hour_sin/cos, day_sin/cos", "Preserves the circular nature of hours and weekdays"],
        ["Lags", "1, 2, 3, 6, 12, 24, 48, 72, 168, 336 hours", "Provides recent and weekly historical load context"],
        ["Rolling", "24-hour mean and standard deviation", "Summarizes recent demand level and volatility"],
        ["Weather", "Temperature, Humidity, WindSpeed, Pressure, CloudCover", "Represents external demand drivers"],
    ], columns=["Feature family", "Variables", "Purpose"])
    st.dataframe(groups, hide_index=True, use_container_width=True)
    st.info("Rolling features are shifted by one hour. Forecast-time calendar/weather predictors are aligned to the target time (t + 24h).")
    if artifact(PROCESSED_FILE, "Run the model pipeline to generate processed_data.csv."):
        processed = load_csv(str(PROCESSED_FILE))
        st.caption(f"Processed data: {len(processed):,} rows × {len(processed.columns):,} columns")
        st.dataframe(processed.head(100), use_container_width=True)


def model_and_evaluation() -> None:
    st.title("XGBoost model & evaluation")
    st.code("XGBRegressor(n_estimators=900, learning_rate=0.035, max_depth=7,\n             subsample=0.85, colsample_bytree=0.9, early_stopping_rounds=50)", language="python")
    st.write("The model is trained on forecast origins whose targets precede 2017-01-01; later target timestamps form the chronological test set.")
    if artifact(OUTPUT_DIR / "model_comparison.csv", "Run `python -m src.model_xgboost` to view evaluation."):
        comparison = pd.read_csv(OUTPUT_DIR / "model_comparison.csv")
        st.markdown("### Benchmark comparison")
        st.dataframe(comparison.round(3), hide_index=True, use_container_width=True)
        chart = px.bar(comparison, x="model", y=["MAE_MW", "RMSE_MW"], barmode="group", title="Error comparison (lower is better)")
        st.plotly_chart(chart, use_container_width=True)
    columns = st.columns(2)
    with columns[0]:
        if (OUTPUT_DIR / "predictions_plot.png").exists(): st.image(str(OUTPUT_DIR / "predictions_plot.png"), caption="Actual vs direct 24-hour forecast")
    with columns[1]:
        if (OUTPUT_DIR / "residuals_plot.png").exists(): st.image(str(OUTPUT_DIR / "residuals_plot.png"), caption="Residual distribution")
    if artifact(OUTPUT_DIR / "feature_importance.csv", "No feature importance file yet."):
        importance = pd.read_csv(OUTPUT_DIR / "feature_importance.csv").head(15).sort_values("importance")
        st.plotly_chart(px.bar(importance, x="importance", y="feature", orientation="h", title="Top 15 XGBoost feature importances"), use_container_width=True)


def architecture() -> None:
    st.title("Architecture, ER diagram & project structure")
    st.markdown("### Data lineage / ER-style diagram")
    st.graphviz_chart('''digraph {
        rankdir=LR; bgcolor="transparent"; node [shape=box style="rounded,filled" fillcolor="#eaf3fb" color="#2878b5" fontname="Arial"];
        energy [label="PJME_hourly.csv\\nDatetime (PK)\\nPJME_MW"];
        weather [label="weather_data.csv\\nDatetime (PK)\\nTemperature, Humidity, WindSpeed\\nPressure, CloudCover"];
        processed [label="processed_data.csv\\nDatetime (PK)\\nenergy + weather + engineered features\\ntarget_24h"];
        model [label="XGBoost model JSON\\n24-hour demand predictor"];
        outputs [label="outputs/\\nmetrics, predictions, importance, charts"];
        energy -> processed [label="join on Datetime"];
        weather -> processed [label="join on Datetime"];
        processed -> model [label="train / chronological test"];
        model -> outputs [label="predict + evaluate"];
    }''', use_container_width=True)
    st.caption("`Datetime` is the shared time-series key. The processed dataset is a denormalized feature table used for model training.")
    st.markdown("### File structure")
    st.code('''energy_forecast_project/
├── PJME_hourly.csv                 # raw PJM energy data
├── app.py                          # Streamlit dashboard
├── config.py                       # paths and non-secret configuration
├── requirements.txt
├── README.md
├── data/
│   ├── weather_data.csv            # observed/proxy weather inputs
│   └── processed/processed_data.csv
├── models/xgboost_energy_model.json
├── outputs/                        # metrics, predictions, feature charts, EDA
└── src/
    ├── data_pipeline.py            # validate, clean, merge
    ├── weather_api.py              # weather API and fallback
    ├── feature_engineering.py      # calendar, lag, rolling features
    ├── model_xgboost.py            # train and save model
    ├── evaluation.py               # metrics and charts
    └── eda.py                      # exploratory analysis''')
    st.markdown("### Run the project")
    st.code("python -m src.eda\npython -m src.model_xgboost\nstreamlit run app.py", language="powershell")


PAGES = {"Overview": overview, "Data & EDA": data_and_eda, "Weather": weather, "Features": features, "Model & Evaluation": model_and_evaluation, "Architecture": architecture}
with st.sidebar:
    st.title("⚡ Forecasting")
    page = st.radio("Navigate", list(PAGES))
    st.divider()
    st.caption("PJM East · XGBoost · 24-hour direct forecast")
PAGES[page]()
